document.write("<div class=\"site-nav-bg\">");
document.write("    <div class=\"site-nav w1200\">");
document.write("        <p class=\"sn-back-home\">");
document.write("            <i class=\"layui-icon layui-icon-home\"><\/i>");
document.write("            <a href=\"index.html\">控制台<\/a>");
document.write("        <\/p>");
document.write("        <div class=\"sn-quick-menu\">");
document.write("            <div class=\"login\"><a href=\"login.html\">登录<\/a><\/div>");
document.write("            <div class=\"login\"><a href=\"register.html\">注册<\/a><\/div>");
document.write("            <div class=\"sp-cart\"><a href=\"shopping.html\">我的购物<\/a><span>520<\/span><\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("<\/div>");
