document.write("<div class=\"footer\">");
document.write("    <div class=\"ng-promise-box\">");
document.write("        <div class=\"ng-promise w1200\">");
document.write("            <p class=\"text\">");
document.write("                <a class=\"icon1\" href=\"javascript:void(0);\">7天无理由退换货<\/a>");
document.write("                <a class=\"icon2\" href=\"javascript:void(0);\">满99元全场免邮<\/a>");
document.write("                <a class=\"icon3\" style=\"margin-right: 0\" href=\"javascript:void(0);\">100%品质保证<\/a>");
document.write("            <\/p>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <div class=\"mod_help w1200\">");
document.write("        <p>");
document.write("            <a href=\"javascript:void(0);\">关于我们<\/a>");
document.write("            <span>|<\/span>");
document.write("            <a href=\"javascript:void(0);\">帮助中心<\/a>");
document.write("            <span>|<\/span>");
document.write("            <a href=\"javascript:void(0);\">售后服务<\/a>");
document.write("            <span>|<\/span>");
document.write("            <a href=\"javascript:void(0);\">商品资讯<\/a>");
document.write("            <span>|<\/span>");
document.write("            <a href=\"javascript:void(0);\">关于货源<\/a>");
document.write("        <\/p>");
document.write("        <p>新华书店版权所有 &copy; 2020-2024<\/p>");
document.write("    <\/div>");
document.write("<\/div>");
