document.write("<div class=\"header\">");
document.write("    <div class=\"headerLayout w1200\">");
document.write("        <div class=\"headerCon\">");
document.write("            <h1 class=\"mallLogo\">");
document.write("                <a href=\"index.html\" title=\"新华书店\">");
document.write("                    <img src=\"img\/logo.png\" width=\"100px\">");
document.write("                <\/a>");
document.write("            <\/h1>");
document.write("            <div class=\"mallSearch\">");
document.write("                <form action=\"index.html\" class=\"layui-form\">");
document.write("                    <input type=\"text\" name=\"keyword\" required lay-verify=\"required\" autocomplete=\"off\"");
document.write("                           class=\"layui-input\" placeholder=\"请输入需要的商品\">");
document.write("                    <button class=\"layui-btn\" lay-submit lay-filter=\"formDemo\">");
document.write("                        <i class=\"layui-icon layui-icon-search\"><\/i>");
document.write("                    <\/button>");
document.write("                    <input type=\"hidden\" name=\"\" value=\"\">");
document.write("                <\/form>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("<\/div>");
