document.write("<div class=\"layui-side layui-bg-black\">");
document.write("    <div class=\"layui-side-scroll\">");
document.write("        <ul class=\"layui-nav layui-nav-tree\">");
document.write("            <li class=\"layui-nav-item layui-nav-itemed\">");
document.write("                <a href=\"javascript:void(0);\">商品信息<\/a>");
document.write("                <dl class=\"layui-nav-child\">");
document.write("                    <dd><a href=\"javascript:void(0);\">商品列表<\/a><\/dd>");
document.write("                    <dd><a href=\"javascript:void(0);\">商品类目<\/a><\/dd>");
document.write("                <\/dl>");
document.write("            <\/li>");
document.write("            <li class=\"layui-nav-item\">");
document.write("                <a href=\"javascript:void(0);\">订单信息<\/a>");
document.write("                <dl class=\"layui-nav-child\">");
document.write("                    <dd><a href=\"javascript:void(0);\">订单列表<\/a><\/dd>");
document.write("                <\/dl>");
document.write("            <\/li>");
document.write("            <li class=\"layui-nav-item\"><a href=\"\">统计<\/a><\/li>");
document.write("        <\/ul>");
document.write("    <\/div>");
document.write("<\/div>");
