document.write("<div class=\"layui-side layui-bg-black\">");
document.write("    <div class=\"layui-side-scroll\">");
document.write("        <ul class=\"layui-nav layui-nav-tree\">");
document.write("            <li class=\"layui-nav-item layui-nav-itemed\">");
document.write("                <a href=\"javascript:void(0);\">ADMIN<\/a>");
document.write("                <dl class=\"layui-nav-child\">");
document.write("                    <dd><a href=\"product.html\">商品列表<\/a><\/dd>");
document.write("                    <dd><a href=\"order.html\">订单列表<\/a><\/dd>");
document.write("                    <dd><a href=\"category.html\">分类管理<\/a><\/dd>");
document.write("                <\/dl>");
document.write("            <\/li>");
document.write("            <li class=\"layui-nav-item layui-nav-itemed\">");
document.write("                <a href=\"javascript:void(0);\">BOARD<\/a>");
document.write("                <dl class=\"layui-nav-child\">");
document.write("                    <dd><a href=\"" + API + "druid\/index.html\">Druid<\/a><\/dd>");
document.write("                    <dd><a href=\"" + API + "swagger-ui.html\">Swagger<\/a><\/dd>");
document.write("                <\/dl>");
document.write("            <\/li>");
document.write("        <\/ul>");
document.write("    <\/div>");
document.write("<\/div>");
